# coding: utf-8

"""
    Terminology Hub Terminology Terminology API

    <div>API documentation for the interacting with terminologies and concepts. <hr width=\"100%\" /><p>For a guided tour of using this API, see our github project <a target=\"_blank\" href=\"https://github.com/terminologyhub/termhub-in-5-minutes\">https://github.com/terminologyhub/termhub-in-5-minutes</a></p><hr width=\"100%\" /><p>For a local runtime container version of this API, see github project <a href=\"https://github.com/terminologyhub/open-termhub\">https://github.com/terminologyhub/open-termhub</a></p><hr width=\"100%\" /><p>Watch the video documentation on the right for more info on using is API documentation page</p></div><div id=\"video-destination\"></div>

    The version of the OpenAPI document: 1.0.0
    Contact: info@terminologyhub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from termhub.api.history_api import HistoryApi


class TestHistoryApi(unittest.TestCase):
    """HistoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HistoryApi()

    def tearDown(self) -> None:
        pass

    def test_export_terminology_history_new_concepts(self) -> None:
        """Test case for export_terminology_history_new_concepts

        Exports terminology concepts added since prior version
        """
        pass

    def test_export_terminology_history_retired_concepts(self) -> None:
        """Test case for export_terminology_history_retired_concepts

        Exports terminology concepts retired since prior version
        """
        pass

    def test_get_terminology_history_new_concepts(self) -> None:
        """Test case for get_terminology_history_new_concepts

        Get terminology concepts added since prior version
        """
        pass

    def test_get_terminology_history_retired_concepts(self) -> None:
        """Test case for get_terminology_history_retired_concepts

        Get terminology concepts retired since prior version
        """
        pass


if __name__ == '__main__':
    unittest.main()
