/*
 * Terminology Hub Terminology Terminology API
 * <div>API documentation for the interacting with terminologies and concepts. <hr width=\"100%\" /><p>For a guided tour of using this API, see our github project <a target=\"_blank\" href=\"https://github.com/terminologyhub/termhub-in-5-minutes\">https://github.com/terminologyhub/termhub-in-5-minutes</a></p><hr width=\"100%\" /><p>For a local runtime container version of this API, see github project <a href=\"https://github.com/terminologyhub/open-termhub\">https://github.com/terminologyhub/open-termhub</a></p><hr width=\"100%\" /><p>Watch the video documentation on the right for more info on using is API documentation page</p></div><div id=\"video-destination\"></div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@terminologyhub.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package api;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import api.invoker.ApiException;
import api.model.AuthResponse;
import api.model.ResultListSubset;
import api.model.ResultListSubsetMember;
import api.model.Subset;
import api.model.SubsetMember;

/**
 * API tests for SubsetApi
 */
public class SubsetApiTest {

    private final SubsetApi api = new SubsetApi();

    @BeforeEach
    public void setUp() {
        // Set up the API client with authentication
        String grantType = "username_password";
        String username = System.getProperty("username");
        String password = System.getProperty("password");
        String accessToken = null;
        try {
            AuthResponse response = new AuthApi().auth(grantType, username, password);
            accessToken = response.getAccessToken();
        } catch (Exception e) {
            e.printStackTrace();
            Assertions.fail("Failed to authenticate: " + e.getMessage());
        }
        api.getApiClient().setBearerToken(accessToken);

    }

    /**
     * Export project subset
     *
     * Exports specified project subset in the specified format.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void exportProjectSubsetTest() throws ApiException {
        //String idOrUriLabel = null;
        //String subset = null;
        //String format = null;
        //byte[] response = api.exportProjectSubset(idOrUriLabel, subset, format);
        // TODO: test validations
    }

    /**
     * Export members for project subset
     *
     * Exports members matching specified search criteria.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void exportProjectSubsetMembersTest() throws ApiException {
        //String idOrUriLabel = null;
        //String subset = null;
        //String query = null;
        //Boolean active = null;
        //File response = api.exportProjectSubsetMembers(idOrUriLabel, subset, query, active);
        // TODO: test validations
    }

    /**
     * Export members for subset
     *
     * Exports members matching specified search criteria.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void exportSubsetMembersTest() throws ApiException {
        //String id = null;
        //String query = null;
        //Boolean active = null;
        //File response = api.exportSubsetMembers(id, query, active);
        // TODO: test validations
    }

    /**
     * Find members across project subsets
     *
     * Finds members matching specified search criteria.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findProjectSubsetMembersTest() throws ApiException {
        String idOrUriLabel = "sandbox";
        String subset = "57d8f6ee-a79c-4dba-b831-8ff6044cdfe6"; // SNOMEDCT_US-MODEL
        String query = "description";
        Integer offset = null;
        Integer limit = 5;
        String sort = null;
        Boolean ascending = null;
        Boolean active = null;
        ResultListSubsetMember response = api.findProjectMembers(idOrUriLabel, subset, query, offset, limit, sort, ascending, active);
        assertNotNull(response);
        assertNotNull(response.getItems());
        assertTrue(response.getItems().size() >= 0);
        assertTrue(response.getItems().size() <= 5);
        for (SubsetMember item : response.getItems()) {
            assertNotNull(item);
            assertNotNull(item.getName());
            assertTrue(item.getName().toLowerCase().contains("description"));
        }
        // TODO: test validations
    }

    /**
     * Get members for the specified project subset
     *
     * Gets members for the specified project subset and the specified search criteria.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSubsetMembersTest() throws ApiException {
        String idOrUriLabel = "sandbox";
        String subset = "57d8f6ee-a79c-4dba-b831-8ff6044cdfe6"; // SNOMEDCT_US-MODEL
        String query = null;
        Integer offset = null;
        Integer limit = null;
        String sort = null;
        Boolean ascending = null;
        Boolean active = null;
        ResultListSubsetMember response = api.findProjectSubsetMembers(idOrUriLabel, subset, query, offset, limit, sort, ascending, active);
        assertNotNull(response);
        assertNotNull(response.getItems());
        assertTrue(response.getItems().size() >= 0);
        for (SubsetMember item : response.getItems()) {
            assertNotNull(item);
            assertNotNull(item.getSubset());
            assertTrue(item.getPublisher().toLowerCase().equals("sandbox"));
            assertTrue(item.getSubset().getAbbreviation().toLowerCase().contains("snomedct_us-model"));
        }
        // TODO: test validations
    }

    /**
     * Find members for the specified subset
     *
     * Finds members for the specified subset and the specified search criteria.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findSubsetMembersTest() throws ApiException {
        //String id = null;
        //String query = null;
        //Integer offset = null;
        //Integer limit = null;
        //String sort = null;
        //Boolean ascending = null;
        //Boolean active = null;
        //ResultListSubsetMember response = api.findSubsetMembers(id, query, offset, limit, sort, ascending, active);
        // TODO: test validations
    }

    /**
     * Find subsets
     *
     * Finds subsets matching specified criteria.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findSubsetsTest() throws ApiException {
        String query = null;
        Integer offset = null;
        Integer limit = null;
        String sort = null;
        Boolean ascending = null;
        ResultListSubset response = api.findSubsets(query, offset, limit, sort, ascending);
        assertNotNull(response);
        assertNotNull(response.getItems());
        assertTrue(response.getItems().size() >= 0);
        // TODO: test validations
    }

    /**
     * Get project subsets
     *
     * Gets subset objects used by the specified project.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProjectSubsetsTest() throws ApiException {
        String idOrUriLabel = "sandbox";
        List<Subset> response = api.getProjectSubsets(idOrUriLabel);
        assertNotNull(response);
        assertTrue(response.size() >= 0);
        // check that each item has "sandbox" as publisher
        for (Subset subset : response) {
            assertNotNull(subset);
            assertNotNull(subset.getPublisher());
            assertTrue(subset.getPublisher().toLowerCase().contains("sandbox"));
        }
    }

    /**
     * Get subset by id
     *
     * Gets subset for the specified id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSubsetTest() throws ApiException {
        String id = "57d8f6ee-a79c-4dba-b831-8ff6044cdfe6";
        Subset response = api.getSubset(id);
        assertNotNull(response);
        assertNotNull(response.getId());

        assertTrue(response.getId().toString().equals(id));
        // TODO: test validations
    }

    /**
     * Export subset
     * 
     * Exports specified subset in the specified format.
     * 
     * @throws ApiException if the Api call fails
     * 
     */
    @Test
    public void exportSubsetTest() throws ApiException {
        String idOrUriLabel = "sandbox";
        String mapset = "SNOMEDCT_US-MODEL";
        String format = "native";
        byte[] response;
        response = api.exportProjectSubset(idOrUriLabel, mapset, format);
        assertNotNull(response);
        assertTrue(response.length > 0);
        // write the response to a file
        try {
            FileOutputStream fos = new FileOutputStream("SNOMEDCT_US-MODEL.zip");
            fos.write(response);
            fos.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            Assertions.fail("Failed to write file: " + e.getMessage());
        } catch (IOException e) {
            e.printStackTrace();
            Assertions.fail("Failed to write file: " + e.getMessage());
        }
        // Verify the file was created
        File file = new File("SNOMEDCT_US-MODEL.zip");
        assertTrue(file.exists(), "File should exist");
        assertTrue(file.length() > 0, "File should not be empty");
    }

}
