/*
 * Terminology Hub Terminology Terminology API
 * API documentation for the interacting with terminologies and concepts. <p>For a guided tour of using this API, see our github project <a target=\"_blank\" href=\"https://github.com/terminologyhub/termhub-in-5-minutes\">https://github.com/terminologyhub/termhub-in-5-minutes</a></p>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@terminologyhub.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package api;

import api.invoker.*;
import api.invoker.auth.*;
import api.model.AuthResponse;
import api.model.ResultListTerminology;
import api.model.Terminology;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.type.TypeReference;

import org.junit.jupiter.api.Assertions;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Disabled;

import java.io.FileOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TerminologyApi
 */
public class TerminologyApiTest {

    private final TerminologyApi api = new TerminologyApi();

    @BeforeEach
    public void setUp() {
        // Set up the API client with authentication
        String grantType = "username_password";
        String username = System.getProperty("username");
        String password = System.getProperty("password");
        String accessToken = null;
        try {
            AuthResponse response = new AuthApi().auth(grantType, username, password);
            accessToken = response.getAccessToken();
        } catch (Exception e) {
            e.printStackTrace();
            Assertions.fail("Failed to authenticate: " + e.getMessage());
        }
        api.getApiClient().setBearerToken(accessToken);
    }

    /**
     * Export terminology
     *
     * Exports specified terminology in the specified format.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void exportTerminologyTest() throws ApiException {
        String idOrUriLabel = "sandbox";
        String terminology = "SNOMEDCT";
        String format = "native";
        byte[] response = api.exportTerminology(idOrUriLabel, terminology, format);
        assertNotNull(response);
        assertTrue(response.length > 0);

        // write the response to a file
        try {
            FileOutputStream fos = new FileOutputStream("SNOMEDCT.zip");
            fos.write(response);
            fos.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            Assertions.fail("File not found: " + e.getMessage());
        } catch (IOException e) {
            e.printStackTrace();
            Assertions.fail("IO Exception: " + e.getMessage());
        }
    }

    /**
     * Find terminologies
     *
     * Finds terminologies matching specified criteria.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findTerminologiesTest() throws ApiException {
        String query = null;
        Integer offset = null;
        Integer limit = null;
        String sort = null;
        Boolean ascending = null;
        ResultListTerminology response = api.findTerminologies(query, offset, limit, sort, ascending);
        assertNotNull(response);
        assertNotNull(response.getItems());
        System.out.println("Response: " + response);
        assertTrue(response.getItems().size() > 0);
        
    }

    /**
     * Get project terminologies
     *
     * Gets terminology objects used by the specified project.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProjectTerminologiesTest() throws ApiException {
        String idOrUriLabel = "sandbox";
        List<Terminology> response = api.getProjectTerminologies(idOrUriLabel);
        assertNotNull(response);
        assertTrue(response.size() > 0);
        System.out.println("Response: " + response);
        for (Terminology terminology : response) {
            assertNotNull(terminology.getId());
            assertNotNull(terminology.getName());
            assertNotNull(terminology.getVersion());
            assertNotNull(terminology.getPublisher());
            assertNotNull(terminology.getPublisher(), "SANDBOX");
        }
    }

    /**
     * Get terminology by id
     *
     * Gets terminology for the specified id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTerminologyTest() throws ApiException {
        String id = "e04c9251-e493-4b5a-b500-f36163625d1f";
        Terminology response = api.getTerminology(id);
        assertNotNull(response);
        System.out.println("Response: " + response);
        assertNotNull(response.getId());
        assertEquals(id, response.getId().toString());
        assertNotNull(response.getName());
        assertNotNull(response.getVersion());
        assertNotNull(response.getAbbreviation());
        assertEquals(response.getAbbreviation(), "ICD10CM");
    }

}
